### ISSUE TITLE
Tests fail on machines that don't have /usr/bin/zip

### ISSUE THREAD

**Issue by peti** [jgm/zip-archive#21]
That path shouldn't be hard-coded. IMHO, the best way to remedy this issue is to call `zip` and rely on `$PATH` to find the program. Also, the `zip` utility should be added to the `build-tools` stanza of the test suite.

**Comment by jgm** [comment]
+++ Peter Simons [Jan 20 15 07:23 ]:
>   That path shouldn't be hard-coded. IMHO, the best way to remedy this
>   issue is to call zip and rely on $PATH to find the program. Also, the
>   zip utility should be added to the build-tools stanza of the test
>   suite.

This doesn't work.

setup-Simple-Cabal-1.22.0.0-i386-linux-ghc-7.6.3: Unknown
build tool zip

But I'll remove the hard-code path.
