### ISSUE TITLE
mismatch between local and central GPF bit

### ISSUE THREAD

**Issue by mhabsaoui** [jgm/zip-archive#33]
Hi,
**info:**  UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

**problem:**  i'm having this issue every while extracting with unzip under linux

`Fetched 162 kB in 0s (584 kB/s)
(Reading database ... 17571 files and directories currently installed.)
Preparing to unpack .../unzip_6.0-16+deb8u3_amd64.deb ...
Unpacking unzip (6.0-16+deb8u3) over (6.0-16+deb8u2) ...
Processing triggers for mime-support (3.58) ...
Setting up unzip (6.0-16+deb8u3) ...
Archive:  /VOCBENCH.zip
  inflating: /vocbench/README.txt
  inflating: /vocbench/vocbench-2.4.4.war
  inflating: /vocbench/semanticturkey-0.12.2+vb-bundle-2.4.4.zip
Archive:  /vocbench/semanticturkey-0.12.2+vb-bundle-2.4.4.zip
file #1 (semanticturkey-0.12.2-2017-03-02/):
         mismatch between local and central GPF bit 11 ("UTF-8"),
         continuing with central flag (IsUTF8 = 1)
file #2 (semanticturkey-0.12.2-2017-03-02/bin/):
         mismatch between local and central GPF bit 11 ("UTF-8"),
         continuing with central flag (IsUTF8 = 1)
......
 `

PS: i've tested this process on another PC and i don't have this issue. Is this archive corruption/rights OR unzip crypto related ?

Thanks

**Comment by jgm** [comment]
How did you create the archive?  Using what version of
zip-archive?

+++ mhabsaoui [May 18 17 05:52 ]:

**Comment by mhabsaoui** [comment]
The archive already existed, dl from here 
=> https://bitbucket.org/art-uniroma2/vocbench2/downloads/VOCBENCH_2.4.4.zip

So don't know with what version they zipped...

**Comment by jgm** [comment]
How do you know it was produced using this library?

+++ mhabsaoui [May 18 17 06:18 ]:

**Comment by mhabsaoui** [comment]
not sure if it's this ZIP libray that the VOCBENCH team used to make their zipped package :)

i thought this library was the official zip once, but  wrong maybe... Sorry. ^^
