### ISSUE TITLE
Could zip-archive use build-type: Simple

### ISSUE THREAD

**Issue by phadej** [jgm/zip-archive#51]
`build-tool: unzip` should already verify that `unzip` is there for tests. Having `build-type: Simple` will simplify some things.

*EDIT:* also to be sure, `test-suite` could try to run `unzip --version` to test it's there, and make test fail early.

One of the things is development of `cabal-install`, which is sadly affected `build-type: Custom` packages. Cross compiling is other. And in general `build-type: Custom` packages are difficult. cc @hvr

I'd be happy to make a PR, if this sounds right.

**Comment by jgm** [comment]
It didn't used to be the case that `build-tool: unzip` would verify the existence of `unzip` without the special addition of `unzip` to hookedPrograms.  Has this changed?
I don't see `unzip` in the list here: https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/Program/Builtin.hs

I have no objections to a PR running `unzip --version` early, and perhaps issuing an informative message if it fails.

> One of the things is development of cabal-install, which is sadly affected build-type: Custom packages. Cross compiling is other. And in general build-type: Custom packages are difficult.

I'm not sure I understand.  `cabal-install` has always supported `build-type: Custom` in the past.

**Comment by phadej** [comment]
> I'm not sure I understand. cabal-install has always supported build-type: Custom in the past.

It does. The problem is small inconvenience in the development setup of `cabal-install`. As `cabal-install` the tool, and the `Cabal` the library is developed together; the development version of `Cabal` is used to run the custom setup of `zip-archive` (which is a dependency of `cabal-install`). In summary it means that one needs to recompile `zip-archive` every time changes are made to `Cabal`; `Cabal` and `cabal-install` are often modified together.

---

It seems that `build-tools: unzip` indeed does nothing. I opened an issue https://github.com/haskell/cabal/issues/5726 to remove this field, as it causes confusion, and tricks many (I thought I knew how `cabal-install` works, I don't).

**Comment by jgm** [comment]
Ah! I see -- you're referring to the fact that `zip-archive` is a dependency of `cabal-install`. I didn't realize that.

**Comment by jgm** [comment]
For some background see #41.

I'm tempted just to remove the test that requires the external tool `unzip`.
I do think it's desirable to make this package easy to install, and to avoid problems building `cabal-install`.

**Comment by jgm** [comment]
This is done.  @peti will you be content with this solution?
(Build-type is simple, 'unzip' not specified in build-tools; however, the tests don't fail if 'unzip' is not in the path; instead, the relevant test is simply skipped.)

**Comment by peti** [comment]
Why did you remove `build-tool: unzip`? You can keep that dependency and still switch to `build-type: simple`. Modern versions of Cabal should support that just fine; it's only older compilers that need a customized `Setup.hs` build system to cope with the dependency on `unzip`.

If you drop the dependency declaration from the Cabal file, it means that environments which don't have `unzip` in scope by default will not execute your test suite properly. That doesn't seem desirable?

**Comment by jgm** [comment]
> Modern versions of Cabal should support that just fine; it's only older compilers that need a customized Setup.hs build system to cope with the dependency on unzip.

Are you sure about that?  I just checked this recently and found the opposite.

**Comment by jgm** [comment]
Also: Which cabal versions are you talking about?

**Comment by peti** [comment]
My guess is that `build-tools: unzip` won't produce that error/warning because the tools is in `$PATH`, so `cabal-install` doesn't need to worry about installing it.

I've experimented with `cabal-install version 2.4.1.0` a bit, too, and my impression is that `build-tools: unzip` has no effect whatsoever when `build-type: simple` is set. Both `v1-test` and `new-test` succeed regardless of whether `unzip` is on path or not.

**Comment by jgm** [comment]
> has no effect whatsoever

Yes, that's what I was saying.  It doesn't prevent the tests from being run when 'unzip' is not present on the path.  So I'm happy to include it, but it's not doing anything except serving as documentation, and it might even be misleading in that capacity...

**Comment by peti** [comment]
Yeah, one would need a `custom` build system to handle the tool's absence properly, e.g. by failing with a meaningful error message.

**Comment by jgm** [comment]
Peter Simons <notifications@github.com> writes:

> Yeah, one would need a `custom` build system to handle the tool's absence properly, e.g. by failing with a meaningful error message.

Exactly: that was what we had with the custom build-type, and that is what we're losing by removing it.

**Comment by peti** [comment]
Which begets the question: what exactly are we *gaining* by switch to `build-type: simple`?

Easier support for cross-compilation is one thing I can think of. Anything else?

**Comment by phadej** [comment]
> Which begets the question: what exactly are we gaining by switching to build-type: simple?

`build-type: Simple` packages are *simpler* to use in complicated environments, like the development of `cabal-install` (this issue), or cross-compilation #53

Looks like @jgm switched to `build-type: Simple`in `master`. Thanks!

**Comment by jgm** [comment]
Peter Simons <notifications@github.com> writes:

> For me, personally, that would be unacceptable in my own code. I would not want test coverage to disappear silently just because the environment changes. There is no guarantee that `unzip` will always be found in `$PATH` by default on Travis-CI. If they were to change their build environment in a way that violates this assumption, then you would never know. The test just wouldn't be run. That doesn't feel like a particularly robust engineering practice to me.

Look, it's a compromise.  It's not ideal, but this is
a way to satisfy the people who need build-type:
simple.  (As a build-dependency of cabal-install,
zip-archive is in a special position.)  Since I test
every change on my own system, I'm 100% confident the
unzip test will be run.  Indeed, if there were any
worries, we could simply add to the travis script
something that installs unzip.

**Comment by jgm** [comment]
John MacFarlane <jgm@berkeley.edu> writes:

> Look, it's a compromise.  It's not ideal, but this is
> a way to satisfy the people who need build-type:
> simple.  (As a build-dependency of cabal-install,
> zip-archive is in a special position.)  Since I test
> every change on my own system, I'm 100% confident the
> unzip test will be run.  Indeed, if there were any
> worries, we could simply add to the travis script
> something that installs unzip.

Let me add that in my view, this is a problem with
cabal/cabal-install.  It should not require custom
Haskell code with special hooks just to tell the build
system that an external program is necessary to run
the tests.  It would be easy for them to fix this issue.
I hope that the cabal-install developers who requested
this change will take this into account.
