### ISSUE TITLE
cross compiling zip-archive 0.3.3

### ISSUE THREAD

**Issue by 2i3r** [jgm/zip-archive#54]
I'm trying to cross-compile `zip-archive` as a build dependency to `pandoc`.
I use my specially compiled `ghc` which produce `armhf` binaries, through `cabal` using command bellow:
```
cabal new-build \
    --builddir=dist/arm-linux-gnueabihf \
    --with-ghc=arm-linux-gnueabihf-ghc \
    --with-ghc-pkg=arm-linux-gnueabihf-ghc-pkg \
    --with-gcc=arm-linux-gnueabihf-clang \
    --with-ld=arm-linux-gnueabihf-ld \
    --hsc2hs-options=--cross-compile \
    --disable-shared \
    --configure-option=--host=arm-linux-gnueabihf
```
The build failes, right after successfully compiling the `setup` binary from `Setup.hs`, by following errors:
```
`./dist/arm-linux-gnueabihf/build/arm-linux/ghc-8.6.3/zip-archive-0.3.3/setup/setup: 1: ./dist/arm-linux-gnueabihf/build/arm-linux/ghc-8.6.3/zip-archive-0.3.3/setup/setup: Syntax error: word unexpected (expecting ")")`
```
(just for simplicity I replaced full path to `zip-archive-0.3.3` by `.`)
no more information I can find using `-v` flag to `cabal`, however here is the full ouput: [pastebin](https://pastebin.com/ipSsECgr)
I'm guessing the `setup` binary is part of build life-cycle, and it fails to run on build machine as it cross-compiled, however I don't know how to check and/or resolve this, may be manual compile and installing?!

```
$ file ./dist/arm-linux-gnueabihf/build/arm-linux/ghc-8.6.3/zip-archive-0.3.3/setup/setup
./dist/arm-linux-gnueabihf/build/arm-linux/ghc-8.6.3/zip-archive-0.3.3/setup/setup: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, with debug_info, not stripped

$ uname -m
x86_64

$ arm-linux-gnueabihf-ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.3

$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
```

**Comment by jgm** [comment]
Try it with zip-archive-0.4 which no longer has a custom Setup.hs.

**Comment by 2i3r** [comment]
Thank you, yes, it works, and I'm sorry as I must have been check that before. 
Even I saw the #51 but missed the commit.

**Comment by 2i3r** [comment]
Sorry again I'm follow this, I'm having same problem with the `pandoc` cross compiles. 
I looked at [50595c8](https://github.com/jgm/zip-archive/commit/50595c8a1a871081802e4d7f942a9c280890bbb3), which replace `Custom` build type to `Simple`. can I do the same with `pandoc`? any other idea?

**Comment by 2i3r** [comment]
Thanks for your response. I found the [@haskell/cabal #1493](https://github.com/haskell/cabal/issues/1493) which seems cabal guys has been look into this, but no progress apparently going on. 
I changed the build type and it seems to start working, unless, `ghc` need `-fexternal-interpreter` to compile `TH` codes, now I'm working on getting `iserv-proxy` working on.
