### ISSUE TITLE
test-zip-archive: which: does not exist

### ISSUE THREAD

**Issue by itd0** [jgm/zip-archive#62]
Hi,

on systems without `which` (which is [non-standard](https://github.com/koalaman/shellcheck/wiki/SC2230)), the test suite fails with:

```
Running 1 test suites...
Test suite test-zip-archive: RUNNING...
test-zip-archive: which: rawSystem: posix_spawnp: does not exist (No such file or directory)
```

Please consider using something different, e.g., one of the fixes suggested by [shellcheck](https://github.com/koalaman/shellcheck/wiki/SC2230): `command -v`.

Thanks!

Regards
itd

**Comment by jgm** [comment]
Thanks for the suggestion.
