### ISSUE TITLE
"Couldn't extract ePub file"

### ISSUE THREAD

**Issue by phiresky** [jgm/zip-archive#63]
**Explain the problem.**

pandoc cannot read this epub file. It doesn't give any more information than that one line. I can extract the same epub without issues as a zip file as well as with `ebook-convert` from Calibre.

```
❯ pandoc -i s.epub --verbose
Couldn't extract ePub file
```

**Pandoc version?**
pandoc 3.1, Arch Linux

Input epub file: [Software Design X-Rays Fix Technical Debt with Behavioral Code Analysis by Adam Tornhill.zip](https://github.com/phiresky/ripgrep-all/files/10842355/Software.Design.X-Rays.Fix.Technical.Debt.with.Behavioral.Code.Analysis.by.Adam.Tornhill.zip)

**Comment by jgm** [comment]
Grepping shows that we don't have the signature "P K 07 08" in this file.

**Comment by jgm** [comment]
The documentation says

>   4.3.9.3 Although not originally assigned a signature, the value 
      0x08074b50 has commonly been adopted as a signature value 
      for the data descriptor record.  Implementers SHOULD be 
      aware that ZIP files MAY be encountered with or without this 
      signature marking data descriptors and SHOULD account for
      either case when reading ZIP files to ensure compatibility.

So I guess this is just a case where we don't have a signature.  So I assume the data description is just the last 12 bytes before the start of the next local file (or something else e.g. sig 0x08064b50 or 0x02014b50).

**Comment by mistmist** [comment]
sorry for the inconvenience, thanks @jgm for fixing this! (i was hoping to look into it this weekend)
